# Generated by Django 4.1.4 on 2022-12-16 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("landing", "0003_auto_20170122_1651"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscriber",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
